// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByXmLGx6EV4w1W0VpKXTXSMDTwhXmSEkc',
    appId: '1:1092561785489:web:73bbf6cbed4997340d2530',
    messagingSenderId: '1092561785489',
    projectId: 'louagego-d3a43',
    authDomain: 'louagego-d3a43.firebaseapp.com',
    storageBucket: 'louagego-d3a43.firebasestorage.app',
    measurementId: 'G-01Q1M042QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZn3ZLTI5VYjz2xhRR_R-iE_RFO1km4jc',
    appId: '1:1092561785489:android:2f39d26c010ca69b0d2530',
    messagingSenderId: '1092561785489',
    projectId: 'louagego-d3a43',
    storageBucket: 'louagego-d3a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIvuG57slosSrPY2f8TkuAlT0_wK-3Oc',
    appId: '1:1092561785489:ios:c8cc12637c695db50d2530',
    messagingSenderId: '1092561785489',
    projectId: 'louagego-d3a43',
    storageBucket: 'louagego-d3a43.firebasestorage.app',
    iosBundleId: 'com.example.louageGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIvuG57slosSrPY2f8TkuAlT0_wK-3Oc',
    appId: '1:1092561785489:ios:c8cc12637c695db50d2530',
    messagingSenderId: '1092561785489',
    projectId: 'louagego-d3a43',
    storageBucket: 'louagego-d3a43.firebasestorage.app',
    iosBundleId: 'com.example.louageGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByXmLGx6EV4w1W0VpKXTXSMDTwhXmSEkc',
    appId: '1:1092561785489:web:aab5a2c9869615d30d2530',
    messagingSenderId: '1092561785489',
    projectId: 'louagego-d3a43',
    authDomain: 'louagego-d3a43.firebaseapp.com',
    storageBucket: 'louagego-d3a43.firebasestorage.app',
    measurementId: 'G-VH5R7Z2QE1',
  );
}
